### ISSUE TITLE
"gs_render_by_kiri_engine" not found'

### ISSUE THREAD

**Issue by AlexMorgand** [Kiri-Innovation/3dgs-render-blender-addon#1]
Great stuff! I imported a custom ply and when trying to start camera update I get:

```
KeyError: 'bpy_prop_collection[key]: key "gs_render_by_kiri_engine" not found'
```

Anything that I'm missing?

**Comment by xiaohulihutu** [comment]
LOL, yea, its better to directly download the released zip file.
