### ISSUE TITLE
Track to camera fails on Mac

### ISSUE THREAD

**Issue by 3pointedit** [Kiri-Innovation/3dgs-render-blender-addon#2]
Import success with .ply file from Lumalabs (test of other splatts).
Eevee displays object correctly but faces does not auto orient to camera when I move the camera in "Lock-camera-to-view" mode or any other mode. Camera update is set to continuous in the addon too. I get this python exception:
<img width="985" alt="Screenshot 2024-09-28 at 4 16 34 pm" src="https://github.com/user-attachments/assets/1b12a158-e386-4006-af62-7c3ac0bffd6f">
On a M1 MBP with this version of blender:
![version](https://github.com/user-attachments/assets/2ca4a9ee-14f1-4fce-9ebd-2a975289775f)

**Comment by 3pointedit** [comment]
OK I updated the zip name but it still fails to orient faces to camera

**Comment by 3pointedit** [comment]
Yes I renamed the folder then re-zipped it. So both folder and zip archive are the same

**Comment by 3pointedit** [comment]
Hmmm, I tried it on the PC at work and made sure that I renamed the folder and re-zipped it but it still fails during camera update.
![error pc](https://github.com/user-attachments/assets/187421d0-37d1-4e37-95db-85de93a18a3e)
![version](https://github.com/user-attachments/assets/61c90e42-46af-43c4-843b-e0a64270c0db)

**Comment by 3pointedit** [comment]
OH dear I renamed it incorrectly didn't I... it works fine when i name folder and zip "gs_render_by_kiri_engine"

**Comment by 3pointedit** [comment]
I think so as long as the instruction to rename the download is made clear in docs. Can the download be ammended to the correct folder name? Am I missing something about the downloads available? I just got it from the green download code button

**Comment by xiaohulihutu** [comment]
Yea, i updated the guidance in installation, ill close the issue for now.
