### ISSUE TITLE
Blue menu items ...!?

### ISSUE THREAD

**Issue by PLAN8VR** [Kiri-Innovation/3dgs-render-blender-addon#5]
Hi, I uninstalled this addon as it wasn't working for me, but now all my menu items are left blue?? Which is horrible and I don't know how to change back.

Firstly, can you tell me how to revert back to the original grey colours, without destroying all my other settings please?
and also, why would you make users setting change anyway? that's invasive.

**Comment by wurara7** [comment]
Hi! We made a full tutorial for this addon in https://youtu.be/u6ELrBT6FXw?si=pAkntz8dmhCgZS54. You can find the solution around 8:15 in this video. I hope it helps solve your problem ！ : )

**Comment by PLAN8VR** [comment]
Hi, oh, ok thanks - I'll have to reinstall it to get that option back. thanks for the assistance.
